
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaobservabilitypoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaobservabilitypoc
  template:
    metadata:
      labels:
        app: javaobservabilitypoc
    spec:
      containers:
      - name: javaobservabilitypoc
        image: javaobservabilitypoc:first
        ports:
        - containerPort: 7101
---
apiVersion: v1
kind: Service
metadata:
  name: javaobservabilitypoc
spec:
  type: NodePort
  selector:
    app: javaobservabilitypoc
  ports:
    - protocol: TCP
      port: 7101
      targetPort: 7101
